fix: 现在运行程序前会先检查程序是否可执行

diff --git a/judge b/judge
--- a/judge
+++ b/judge
@@ -42,7 +42,13 @@ done
 program=${*:$OPTIND:1}
 program_basename=$(basename "${program}")
 
-[[ ! ${program} ]] && print_usage_and_exit
+[[ ! "${program}" ]] && print_usage_and_exit
+
+if [[ ! -x "${program}" ]]
+then
+  echo "Cannot execute the program. "
+  exit 1
+fi
 
 tmp_file=$(mktemp)
 
